spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpabook
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: true

logging:
  level:
    org.hibernate.SQL: debug

